name: 'Deploy to EC2'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: pipeline
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./profile_app
      run: npm ci

    - name: Build Application
      working-directory: ./profile_app
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      working-directory: ./profile_app
      run: |
        rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.next/cache' \
          ./ ec2-user@${{ secrets.EC2_HOST }}:/var/www/nextjs/

    - name: Start Application
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} '
          cd /var/www/nextjs && \
          npm ci && \
          pm2 delete nextjs || true && \
          pm2 start npm --name "nextjs" -- start
        '
