name: 'Deploy to EC2'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: pipeline
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './profile_app/package-lock.json'

    - name: Install Dependencies
      working-directory: ./profile_app
      run: npm install --legacy-peer-deps

    - name: Generate Prisma Client
      working-directory: ./profile_app
      run: npx prisma generate --schema=./src/server/prisma/schema.prisma

    - name: Build Application
      working-directory: ./profile_app
      run: npm run build

    - name: Setup SSH with Persistence
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
        # Create SSH config with connection persistence settings
        cat > ~/.ssh/config << EOF
        Host *
          ServerAliveInterval 60
          ServerAliveCountMax 10
          TCPKeepAlive yes
          ControlMaster auto
          ControlPath ~/.ssh/control-%r@%h:%p
          ControlPersist 10m
        EOF
        chmod 600 ~/.ssh/config

    - name: Prepare Deployment Package
      working-directory: ./profile_app
      run: |
        # Create deployment package
        tar --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next/cache' \
            --exclude='src/server/generated' \
            --exclude='.next' \
            -czf /tmp/app.tar.gz .

    - name: Copy to EC2
      run: |
        # Copy with compression and verbose output
        scp -C -v -i ~/.ssh/deploy_key /tmp/app.tar.gz ec2-user@${{ secrets.EC2_HOST }}:~/app.tar.gz

    - name: Extract and Install Dependencies
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} "
          cd ~ && \
          rm -rf app && \
          mkdir app && \
          tar -xzf app.tar.gz -C app && \
          rm app.tar.gz && \
          cd app && \
          if [ ! -f package.json ]; then
            echo 'Error: package.json not found in app directory'
            exit 1
          fi && \
          export NODE_OPTIONS='--max-old-space-size=4096' && \
          npm --prefix ~/app install --legacy-peer-deps"

    - name: Copy Environment File
      working-directory: ./profile_app
      run: |
        # Create .env file from secrets
        echo "Creating .env file from secrets..."
        cat > .env << 'EOF'
DATABASE_URL="${{ secrets.DATABASE_URL }}"
JWT_SECRET="${{ secrets.JWT_SECRET }}"
AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
AWS_REGION="${{ env.AWS_REGION }}"
AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}"
SES_FROM_EMAIL="${{ secrets.SES_FROM_EMAIL }}"
NEXT_PUBLIC_APP_URL="${{ secrets.NEXT_PUBLIC_APP_URL }}"
EOF

        # Verify .env file was created and has content
        if [ ! -s .env ]; then
          echo "Error: .env file is empty or not created"
          ls -la .env
          exit 1
        fi
        
        echo "Copying .env file to EC2..."
        if ! scp -i ~/.ssh/deploy_key .env ec2-user@${{ secrets.EC2_HOST }}:~/app/.env; then
          echo "Failed to copy .env file"
          exit 1
        fi
        echo ".env file copied successfully"


    - name: Generate Prisma and Prepare Build
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} "
          cd ~/app && \
          if [ ! -f package.json ]; then
            echo 'Error: package.json not found in app directory'
            exit 1
          fi && \
          export NODE_OPTIONS='--max-old-space-size=4096' && \
          export NEXT_TELEMETRY_DISABLED=1 && \
          npx --prefix ~/app prisma generate --schema=./src/server/prisma/schema.prisma && \
          rm -rf .next && \
          mkdir -p .next"

    - name: Build Next.js Application
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} "
          cd ~/app && \
          export NODE_OPTIONS='--max-old-space-size=4096' && \
          export NEXT_TELEMETRY_DISABLED=1 && \
          npm --prefix ~/app run build || {
            echo 'Build failed'
            exit 1
          }"

    - name: Deploy with PM2
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} "
          cd ~/app && \
          pm2 delete nextjs || true && \
          pm2 start --cwd ~/app npm --name \"nextjs\" -- start && \
          pm2 save && \
          pm2 list"

    - name: Cleanup
      run: rm -f /tmp/app.tar.gz
